### PR TITLE
Web diagnostics

### PR DESCRIPTION
**Pull request by joshmoore**
Slight refactoring on top of @dominikl's work to provide a discoverable `diagnostics` API.

### CODE REVIEW

**Comment by joshmoore** [comment]
Travis failure is odd. Gradle is being run. Not sure why that's happening.

**Comment by jburel** [comment]
travis failure due to ``version = 'UNKNOWN-ice35'`` so I won't worry too much about it

**Comment by jburel** [comment]
* Build locally with PR
* Both ``bin/omero admin diagnostics`` or  ``bin/omero web diagnostics`` commands are available and give a report
* Install the CLI plugin https://github.com/joshmoore/omero-cli-diagnostics
* Run ``bin/omero diagnostics``
* error `` invalid choice: 'diagnostics'``

**Comment by dominikl** [comment]
Sorry, totally missed that this is a PR against my branch... Shall I merge it, or is it easier to just close mine and you open it against develop? I'm getting a bit confused...

**Comment by jburel** [comment]
Can you merge @joshmoore one in yours?
Josh being away next week it is better to keep your open if more commits are needed

**Pull request merged**
